leftnav:
- identifier: de3c3a71-d600-5928-bb4e-577e0088365c
  name: Syllabus and Calendar
  pageRef: /pages/syllabus
  weight: 10
- identifier: a3c8bebc-6eb9-41af-a004-90f902d06a8a
  name: Instructor Insights
  pageRef: /pages/instructor-insights
  weight: 20
- identifier: af35318d-2434-905c-4e09-59d9c43798ae
  name: Readings
  pageRef: /pages/readings/
  weight: 30
- identifier: fbff7337-c706-c621-94e6-2a5cacd0b9ee
  name: Video Lectures
  pageRef: /video_galleries/video-lectures
  weight: 40
- identifier: e1460b91-78ed-04f1-60e8-9963055ce410
  name: Lecture Slides
  pageRef: /pages/lecture-slides
  weight: 50
- identifier: b2f760a7-6602-c9ba-0080-008ffa2d8c4b
  name: Recitations
  pageRef: /pages/recitations
  weight: 60
- identifier: 731831b3-3564-ab17-c02f-1d9ead7c5f30
  name: Problem Sets
  pageRef: /pages/problemsets
  weight: 70
- identifier: d6d24900-d487-60fe-1187-273500c52e02
  name: Quizzes and Exams
  pageRef: /pages/quizzes_exams
  weight: 80
- identifier: aa03ca14-fe4b-c4e7-4d40-04a339fa46b9
  name: Books of Interest
  pageRef: /pages/readings/books-of-interest
  parent: af35318d-2434-905c-4e09-59d9c43798ae
  weight: 10
